#!/bin/bash
PHP_VERSION="5.4.40"
PHP_SHORT_VERSION="5.4"

PHPBREW_PATH="/root/.phpbrew/"
PHPBREW_PHP_PATH="${PHPBREW_PATH}php/php-5.4.40/"
PHPBREW_MODULE_PATH="${PHPBREW_PATH}modules/"

phpbrew install ${PHP_VERSION} +dev +dbs
rm -R /root/.phpbrew/build/php-${PHP_VERSION}

declare -a module_list=('zendguardloader')

for module_name in "${module_list[@]}"; do
  full_module_name="${PHPBREW_MODULE_PATH}${module_name}"
  destination_file="${PHPBREW_PHP_PATH}lib/php/extensions/${module_name}.so"

  if [[ -f "${full_module_name}.so" ]] || [[ -f "${full_module_name}-php-${PHP_SHORT_VERSION}.so" ]]; then
    if [[ -f "${full_module_name}.so" ]]; then
      source_file="${full_module_name}.so"
    elif [[ -f "${full_module_name}-php-${PHP_SHORT_VERSION}.so" ]]; then
      source_file="${full_module_name}-php-${PHP_SHORT_VERSION}.so"
    fi

    mkdir -p "${PHPBREW_PHP_PATH}lib/php/extensions/"
    cp ${source_file} ${destination_file}

    mkdir -p "${PHPBREW_PHP_PATH}var/db/"
    ini_file="${PHPBREW_PHP_PATH}var/db/${module_name}.ini"
    cp ${full_module_name}.ini ${ini_file}

    sed -i "s|<file>|${destination_file}|g" ${ini_file}
    
    cp ${ini_file} "/etc/php5/apache2/conf.d/"

    if [[ ${module_name} == "tideways" ]]; then
      php_file="${PHPBREW_PHP_PATH}lib/php/extensions/Tideways.php"
      cp ${PHPBREW_MODULE_PATH}Tideways.php ${php_file}
    fi
  fi
done
