variants:
    dev:
        intl:
        cgi:
        bcmath:
        bz2:
        calendar:
        cli:
        ctype:
        dom:
        fileinfo:
        filter:
        ipc:
        json:
        mbregex:
        mbstring:
        mhash:
        mcrypt:
        pcntl:
        pcre:
        pdo:
        phar:
        posix:
        readline:
        sockets:
        tokenizer:
        xml:
        curl:
        zip:
        iconv:
        fpm:
          - --enable-fpm
          - --with-fpm-user=www-data
          - --with-fpm-group=www-data
        openssl:
          - --with-libdir=lib/x86_64-linux-gnu
        soap:
        gd:
          - --with-zlib-dir
          - --with-gd
          - --with-jpeg-dir=/usr
          - --with-png-dir=/usr
    dbs52:
        mysql:
          - --with-mysql=shared,/usr
          - --with-mysqli=shared,/usr/bin/mysql_config
          - --with-pdo-mysql=shared,/usr
          - --with-mysql-sock=/run/mysqld/mysqld.sock
        sqlite:
        pgsql:
        pdo:
extensions:
    dev:
        xhprof: latest
        xdebug: 2.2.7
        memcache: latest